export const baseApiEndpoint = 'https://fn-crossborder-xb-sodimac-dev.azurewebsites.net/api/'
export const baseApiEndpointDev = 'http://localhost:3001'
export const createOrderEndpoint = baseApiEndpointDev + 'order'
export const productsDescriptionEndpoint = baseApiEndpointDev + 'product'
export const shippingMethodEndpoint = baseApiEndpointDev + 'shipping'
export const listOrdersEndpoint = baseApiEndpointDev + 'ordersList'
export const trackingEndpoint = baseApiEndpointDev + 'tracking'
