export const baseApiEndpoint = 'https://fn-crossborder-xb-sodimac-dev.azurewebsites.net/api/'
export const baseApiEndpointDev = 'http://localhost:3001/api/'
export const createOrderEndpoint = baseApiEndpointDev + 'order'
export const productsDescriptionEndpoint = baseApiEndpointDev + 'product'
export const shippingMethodEndpoint = baseApiEndpointDev + 'shipping'
